[package]
name = "filetime_type"
version = "0.1.3"
edition = "2018"
description = "Platform agnostic FILETIME conversion"
license = "MIT"
repository = "https://github.com/OpenXbox/filetime_type-rs"
homepage = "https://openxbox.org"

[dependencies]
chrono = "0.4"
